data:
  # train: MimicIII/Patients/Cuis/
  notes: data/notes/
  # codes: MimicIII/Source/
  codes: data/codes/
  model: data/model/
  embed: Word2VecModels/mimic-cuis.txt

args:
  min_token_freq: 100
  max_tokens_in_file: 10000
  min_examples_per_code: 1000
  test_size: 0.2

dan:
  batch: 50
  epochs: 75
  embdims: 300
  hidden: 1000
  learnrt: 0.001

cnn:
  batch: 50
  epochs: 25
  embdims: 300
  filters: 200
  filtlen: 2
  hidden: 1000
  learnrt: 0.001
