data:
  # train: MimicIII/Patients/Cuis/
  notes: data/notes/
  # codes: MimicIII/Source/
  codes: data/codes/
  model: data/model/
  embed: Word2VecModels/mimic-cuis.txt
  bq: False

args:
  min_token_freq: 100
  max_tokens_in_file: 10000
  min_examples_per_code: 1000
  test_size: 0.2

dan:
  batch: 50
  epochs: 10
  embdims: 300
  hidden: 1000
  learnrt: 0.001
  workers: 0
  cuda: True
  score: macro/f1

# cnn:
#   batch: 50
#   epochs: 25
#   embdims: 300
#   filters: 200
#   filtlen: 2
#   hidden: 1000
#   learnrt: 0.001

eval:
  # alphabet: /data/lookups/alphabet.pkl
  judgement: intuitive
  train_data: data/eval/train/records/
  train_annot: data/eval/train/annotations/obesity_standoff_annotations_training*.xml
  test_data: data/eval/test/records/
  test_annot: data/eval/test/annotations/obesity_standoff_annotations_test_intuitive.xml
  min_token_freq: 0
