data:
  # train: MimicIII/Patients/Cuis/
  notes: data/notes/
  # codes: MimicIII/Source/
  codes: data/codes/
  model: data/model/
  # embed: Word2VecModels/mimic-cuis.txt
  w2v: False
  bq: False

args:
  min_token_freq: 100
  max_tokens_in_file: 10000
  min_examples_per_code: 1000
  test_size: 0.2

dan:
  batch: 50
  epochs: 30
  embdims: 300
  hidden: 1000
  learnrt: 0.001
  workers: 0
  cuda: True
  score: macro/f1

# cnn:
#   batch: 50
#   epochs: 25
#   embdims: 300
#   filters: 200
#   filtlen: 2
#   hidden: 1000
#   learnrt: 0.001

eval:
  # alphabet: /data/lookups/alphabet.pkl
  judgement: intuitive
  train_data: i2b2/extracted_text/Train1+2/
  train_annot: i2b2/Xml/obesity_standoff_annotations_training*.xml
  test_data: i2b2/extracted_text/Test/
  test_annot: i2b2/Xml/obesity_standoff_annotations_test.xml
  alphabet_pickle: i2b2/Model/alphabet.pkl
  alphabet_pickle_learned_model: data/lookups/alphabet.pkl
  model_file: output/model/BaseModel.pth
  min_token_freq: 0
