name: cse6250-project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.10
  - pip
  - pyyaml
  - pandas
  - nltk
  - scikit-learn
  - matplotlib
  - gensim
  - pip:
    - torch
    - packaging
    - tensorboard